
  project 'TLYL.xcodeproj'
  platform :ios, '8.0'
  use_frameworks!
  target 'TLYL'do
  pod 'SDWebImage', '~> 3.7'
  pod 'Masonry', '~> 1.0.2'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'MJExtension', '~> 3.0.13'
  pod 'Alamofire', '~> 4.4.0'
  pod 'MJRefresh'
  pod 'UMengAnalytics'
  pod 'SVProgressHUD'

  end
